version: 2
jobs:
  build_python_27:
    machine: true
    steps:
      - checkout

      - restore_cache:
          key: vx-miniconda-{{ .Branch }}

      - run:
          name: install miniconda
          command: |
            ./.circleci/install_conda.sh

      - save_cache:
          key: v3-miniconda-{{ .Branch }}
          paths:
            - /home/circleci/miniconda

      - run:
          name: Build and test python 2.7
          command: |
            source ~/miniconda/bin/activate root
            cd /home/circleci/project
            conda build --python 2.7 ./conf/conda

      #- run:
      #    name: Upload package
      #    command: |
      #      source ~/miniconda/bin/activate root
      #      cd /home/circleci/project
      #      export CONDA_PY=27
      #      upload_or_check_non_existence ./conf/conda spectralDNS --channel main

  build_python_36:
    machine: true
    steps:
      - checkout

      - restore_cache:
          key: vx-miniconda-{{ .Branch }}

      - run:
          name: install miniconda
          command: |
            ./.circleci/install_conda.sh

      - run:
          name: Build and test python 3.6
          command: |
            source ~/miniconda/bin/activate root
            cd /home/circleci/project
            conda build --python 3.6 ./conf/conda

      #- run:
      #    name: Upload package
      #    command: |
      #      source ~/miniconda/bin/activate root
      #      cd /home/circleci/project
      #      export CONDA_PY=36
      #      upload_or_check_non_existence ./conf/conda spectralDNS --channel main

  build_python_37:
    machine: true
    steps:
      - checkout

      - restore_cache:
          key: vx-miniconda-{{ .Branch }}

      - run:
          name: install miniconda
          command: |
            ./.circleci/install_conda.sh

      - run:
          name: Build and test python 3.7
          command: |
            source ~/miniconda/bin/activate root
            cd /home/circleci/project
            conda build --python 3.7 ./conf/conda

      #- run:
      #    name: Upload package
      #    command: |
      #        source ~/miniconda/bin/activate root
      #        cd /home/circleci/project
      #        export CONDA_PY=37
      #        #export GIT_DESCRIBE_TAG=`git describe --tags | cut -d'-' -f 1`
      #        upload_or_check_non_existence ./conf/conda spectralDNS --channel main

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_python_27
      - build_python_36
      - build_python_37